import { defineBrand } from "@retail-os/brand-config/brand-config";

export const moonConfig = defineBrand({
  identity: {
    key: "moonglasses",
    profile: {
      brandName: "Moonglasses",
      tagline: "Light tints, good vibe",
      voice:
        "Fashion-forward, editorial, confident — dark/nightlife imagery paired with restrained, minimal copy. Short lines, no hard sell.",
      productNoun: "sunglasses",
      currencySymbol: "₹",
      siteUrl: "https://moon-glasses.store",
      instagramHandle: "@moonglassesonline",
    },
    description:
      "Moonglasses™ — fashion eyewear for after dark. The Collection from ₹1,499, the Limited Series from ₹1,999. Ships across India.",
    keywords: ["fashion sunglasses India", "MOON GLASSES", "eyewear"],
    assets: {
      orgLogoPath: "/images/brand/moon-glasses-logo.png",
      navLogoPath: "/images/brand/moon-glasses-logo.png",
      navLogoAlt: "MOON GLASSES",
      ogImagePath: "/images/brand/moon-glasses-logo.png",
    },
  },
  commerce: { currency: "INR" },
  integrations: {
    payment: ["razorpay", "upi"],
    logistics: "shiprocket",
    whatsapp: "msg91",
    meta: true,
  },
  modules: {
    loyalty: true,
    referrals: true,
    journal: true,
    "community-ugc": true,
    "creator-gifting": true,
    "pay-with-a-post": true,
    "ai-ad-briefs": true,
    "performance-manager": true,
    "growth-recommendations": true,
    "business-plan": true,
    "ai-media-gen": true,
    "whatsapp-inbox": true,
    "whatsapp-payment-confirm": true,
    "ux-insights": true,
    "abandoned-cart": true,
    "leads-crm": true,
    preorders: true,
  },
  extensions: [
    {
      key: "explorer-submissions",
      label: "Explorer Submissions",
      classification: "client-extension" as const,
      defaultEnabled: true,
      navGroup: "marketing",
      ownerBrand: "moonglasses",
    },
    {
      key: "models",
      label: "Models (Virtual Try-On)",
      classification: "client-extension" as const,
      defaultEnabled: true,
      navGroup: "products",
      ownerBrand: "moonglasses",
    },
    {
      key: "product-images",
      label: "Product Images",
      classification: "client-extension" as const,
      defaultEnabled: true,
      navGroup: "products",
      ownerBrand: "moonglasses",
    },
    {
      key: "tagged-posts",
      label: "Tagged Posts",
      classification: "client-extension" as const,
      defaultEnabled: true,
      navGroup: "marketing",
      ownerBrand: "moonglasses",
    },
    {
      key: "payment-confirmations",
      label: "WhatsApp Payment Confirmations",
      classification: "client-extension" as const,
      defaultEnabled: true,
      navGroup: "orders",
      ownerBrand: "moonglasses",
    },
    {
      key: "social-instagram",
      label: "Social (Instagram)",
      classification: "client-extension" as const,
      defaultEnabled: true,
      navGroup: "marketing",
      ownerBrand: "moonglasses",
    },
    {
      key: "master-inventory",
      label: "Master Inventory",
      classification: "client-extension" as const,
      defaultEnabled: true,
      navGroup: "inventory-master",
      ownerBrand: "moonglasses",
    },
    {
      key: "team-access",
      label: "Team Access",
      classification: "client-extension" as const,
      defaultEnabled: true,
      navGroup: "settings",
      ownerBrand: "moonglasses",
    },
  ],
});
