import type { Chapter } from "@/types/chapter";

/**
 * MOON GLASSES launch catalogue — sourced from a licensed supplier (Ted
 * Smith) product pack: 6 shapes across 22 colour variants.
 * Every SKU is flat ₹1,499 regardless of frame material.
 */
export const chapters: Chapter[] = [
  {
    slug: "moon-wayfarer-black",
    name: "MOON 01 Wayfarer — Black",
    series: "Plastic",
    folder: "moon-wayfarer-black",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Wayfarer frame in acetate, black lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
  {
    slug: "moon-wayfarer-black-green",
    name: "MOON 02 Wayfarer — Black Green",
    series: "Plastic",
    folder: "moon-wayfarer-black-green",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Wayfarer frame in acetate, black green lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
  {
    slug: "moon-wayfarer-demi-brown-light-brown",
    name: "MOON 03 Wayfarer — Demi-brown Light Brown",
    series: "Plastic",
    folder: "moon-wayfarer-demi-brown-light-brown",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Wayfarer frame in acetate, demi-brown light brown lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
  {
    slug: "moon-round-black",
    name: "MOON 04 Round — Black",
    series: "Plastic",
    folder: "moon-round-black",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Round frame in acetate, black lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
  {
    slug: "moon-round-black-light-brown",
    name: "MOON 05 Round — Black Light Brown",
    series: "Plastic",
    folder: "moon-round-black-light-brown",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Round frame in acetate, black light brown lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
  {
    slug: "moon-round-demi-brown-blue-graded",
    name: "MOON 06 Round — Demi-brown Blue Graded",
    series: "Plastic",
    folder: "moon-round-demi-brown-blue-graded",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Round frame in acetate, demi-brown blue graded lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
  {
    slug: "moon-rectangle-black-orange",
    name: "MOON 07 Rectangle — Black Orange",
    series: "Plastic",
    folder: "moon-rectangle-black-orange",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Rectangle frame in acetate, black orange lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
  {
    slug: "moon-rectangle-black-grey",
    name: "MOON 08 Rectangle — Black Grey",
    series: "Plastic",
    folder: "moon-rectangle-black-grey",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Rectangle frame in acetate, black grey lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
  {
    slug: "moon-rectangle-black-blue",
    name: "MOON 09 Rectangle — Black Blue",
    series: "Plastic",
    folder: "moon-rectangle-black-blue",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Rectangle frame in acetate, black blue lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
  {
    slug: "moon-rectangle-black-purple",
    name: "MOON 10 Rectangle — Black Purple",
    series: "Plastic",
    folder: "moon-rectangle-black-purple",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Rectangle frame in acetate, black purple lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
  {
    slug: "moon-rectangle-black-green",
    name: "MOON 11 Rectangle — Black Green",
    series: "Plastic",
    folder: "moon-rectangle-black-green",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Rectangle frame in acetate, black green lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
  {
    slug: "moon-aviator-classic-demi-brown-grey-graded",
    name: "MOON 12 Aviator — Demi-brown Grey Graded",
    series: "Plastic",
    folder: "moon-aviator-classic-demi-brown-grey-graded",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Aviator frame in acetate, demi-brown grey graded lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
  {
    slug: "moon-aviator-classic-black-black",
    name: "MOON 13 Aviator — Black Black",
    series: "Plastic",
    folder: "moon-aviator-classic-black-black",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Aviator frame in acetate, black black lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
  {
    slug: "moon-aviator-classic-black-yellow",
    name: "MOON 14 Aviator — Black Yellow",
    series: "Plastic",
    folder: "moon-aviator-classic-black-yellow",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Aviator frame in acetate, black yellow lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
  {
    slug: "moon-octagon-silver-light-brown",
    name: "MOON 15 Octagon — Silver Light Brown",
    series: "Metal",
    folder: "moon-octagon-silver-light-brown",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Octagon frame in metal, silver light brown lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
  {
    slug: "moon-octagon-gold-grey",
    name: "MOON 16 Octagon — Gold Grey",
    series: "Metal",
    folder: "moon-octagon-gold-grey",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Octagon frame in metal, gold grey lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
  {
    slug: "moon-octagon-silver-grey",
    name: "MOON 17 Octagon — Silver Grey",
    series: "Metal",
    folder: "moon-octagon-silver-grey",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Octagon frame in metal, silver grey lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
  {
    slug: "moon-octagon-black-blue",
    name: "MOON 18 Octagon — Black Blue",
    series: "Metal",
    folder: "moon-octagon-black-blue",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Octagon frame in metal, black blue lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
  {
    slug: "moon-aviator-metal-black-yellow",
    name: "MOON 19 Aviator (Metal) — Black Yellow",
    series: "Metal",
    folder: "moon-aviator-metal-black-yellow",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Aviator (Metal) frame in metal, black yellow lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
  {
    slug: "moon-aviator-metal-gunmetal-brown",
    name: "MOON 20 Aviator (Metal) — Gunmetal Brown",
    series: "Metal",
    folder: "moon-aviator-metal-gunmetal-brown",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Aviator (Metal) frame in metal, gunmetal brown lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
  {
    slug: "moon-aviator-metal-gold-green",
    name: "MOON 21 Aviator (Metal) — Gold Green",
    series: "Metal",
    folder: "moon-aviator-metal-gold-green",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Aviator (Metal) frame in metal, gold green lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
  {
    slug: "moon-aviator-metal-silver-grey",
    name: "MOON 22 Aviator (Metal) — Silver Grey",
    series: "Metal",
    folder: "moon-aviator-metal-silver-grey",
    images: ["front.jpg", "angle.jpg", "side.jpg"],
    primary: "front.jpg",
    sideImage: "angle.jpg",
    story: "Aviator (Metal) frame in metal, silver grey lens tint.",
    price: 1499,
    verifiedOnSite: true,
  },
];

/** One combined spec list shown on every product page. */
export const SHARED_SPECS = [
  "UV400 Protection — Blocks 100% Of UVA/UVB Rays",
  "Impact-Resistant Lenses",
  "Spring-Hinge Temples For All-Day Comfort",
  "Scratch-Resistant Coating",
  "Includes Microfiber Pouch",
  "One Size Fits Most",
  "Designed In India",
];

/**
 * Drops the "MOON 01"-style SKU code for display — customers see
 * "Wayfarer — Black", the code stays in `name`/`slug` for admin and
 * internal reference only.
 */
export function shortProductName(name: string) {
  return name.replace(/^MOON\s+\d+\s*/, "");
}

/**
 * Real photography lives as "<original stem>_no_bg.png" per product folder.
 */
export function chapterImageSrc(folder: string, file: string) {
  if (/^https?:\/\//.test(file)) return file;

  const dot = file.lastIndexOf(".");
  const stem = dot === -1 ? file : file.slice(0, dot);
  const resolved = `${stem}_no_bg.png`;
  return `/images/chapters/${encodeURIComponent(folder)}/${encodeURIComponent(resolved)}`;
}
